//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceItUp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiceItUpEntities1 : DbContext
    {
        public DiceItUpEntities1()
            : base("name=DiceItUpEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Meetup> Meetups { get; set; }
        public virtual DbSet<MeetupParticipant> MeetupParticipants { get; set; }
        public virtual DbSet<PlayerLogin> PlayerLogins { get; set; }
        public virtual DbSet<PlayerProfile> PlayerProfiles { get; set; }
        public virtual DbSet<PlayerRelationship> PlayerRelationships { get; set; }
        public virtual DbSet<ProfileTitle> ProfileTitles { get; set; }
    }
}
