//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceItUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetupParticipant
    {
        public int meetup_id { get; set; }
        public int player_id { get; set; }
        public Nullable<bool> attended { get; set; }
    
        public virtual Meetup Meetup { get; set; }
        public virtual PlayerLogin PlayerLogin { get; set; }
    }
}
