//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P8Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerRelationship
    {
        public int requester_player_id { get; set; }
        public int respondent_player_id { get; set; }
        public string relationship_state { get; set; }
    
        public virtual PlayerLogin PlayerLogin { get; set; }
        public virtual PlayerLogin PlayerLogin1 { get; set; }
    }
}
